export const FOCUSING = {
  WINDOW: 'WINDOW',
  ICON: 'ICON',
  DESKTOP: 'DESKTOP',
};
export const POWER_STATE = {
  BOOT: 'BOOT',
  LOGON: 'LOGON',
  LOADING: 'LOADING',
  START: 'START',
  LOGGING_OFF: 'LOGGING_OFF',
  SHUTTING_DOWN: 'SHUTTING_DOWN',
  RESTARTING: 'RESTARTING',
  SAFE_SHUTDOWN: 'SAFE_SHUTDOWN',
  LOG_OFF: 'LOG_OFF',
  TURN_OFF: 'TURN_OFF',
  BSOD: 'BSOD',
};
